config.code=232323
config.username=jonas
config.message=Hola como estass ááññ
config.listOfValues=hola,como,estass
config.valuesMap={product:'Cpu Intel Core 7', description:'Alder Lake, 12core, a 5 Ghz', price:'1000'}